apiVersion: v1
kind: Pod
metadata:
  name: model-loader
  namespace: tsl-service
spec:
  containers:
    - name: loader
      image: ubuntu:22.04
      command: ["sleep", "3600"]
      volumeMounts:
        - name: models-volume
          mountPath: /mnt/models
  volumes:
    - name: models-volume
      persistentVolumeClaim:
        claimName: models-pvc
